source "https://rubygems.org"
# Run Jekyll with `bundle exec jekyll serve` to run the site on your local machine.
#
#     bundle exec jekyll serve
#

# Add the just-the-docs theme
gem "just-the-docs"

# For github pages
gem "github-pages", "~> 231", group: :jekyll_plugins

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem 'webrick'
