import taskZen
import time

taskZen.registerDevice('taskZen-minimal')

taskZen.tapKey('KEY_LEFTMETA')
time.sleep(0.25)
taskZen.tapKey('KEY_H', 'KEY_LEFTSHIFT')
time.sleep(0.1)
taskZen.tapKey('KEY_E')
time.sleep(0.1)
taskZen.tapKey('KEY_L')
time.sleep(0.1)
taskZen.tapKey('KEY_L')
time.sleep(0.1)
taskZen.tapKey('KEY_O')
time.sleep(0.1)
taskZen.tapKey('KEY_SPACE')
time.sleep(0.1)
taskZen.tapKey('KEY_W', 'KEY_LEFTSHIFT')
time.sleep(0.1)
taskZen.tapKey('KEY_O')
time.sleep(0.1)
taskZen.tapKey('KEY_R')
time.sleep(0.1)
taskZen.tapKey('KEY_L')
time.sleep(0.1)
taskZen.tapKey('KEY_D')
time.sleep(0.1)
taskZen.tapKey('KEY_1', 'KEY_LEFTSHIFT')
